<?php

namespace Database\Seeders;

use App\Models\View;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ViewSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('views')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $views = [
            ['url' => 'views.index', 'is_menu' => true, 'name' => 'Vistas', 'icon' => 'fas fa-fw fa-eye', 'module_id' => 1],
            ['url' => 'views.create', 'is_menu' => false, 'name' => 'Crear Vista', 'module_id' => 1],
            ['url' => 'views.store', 'is_menu' => false, 'name' => 'Guardar Vista', 'module_id' => 1],
            ['url' => 'views.edit', 'is_menu' => false, 'name' => 'Editar Vista', 'module_id' => 1],
            ['url' => 'views.update', 'is_menu' => false, 'name' => 'Actualizar Vista', 'module_id' => 1],
            ['url' => 'views.delete', 'is_menu' => false, 'name' => 'Eliminar Vista', 'module_id' => 1],
            ['url' => 'roles.index', 'is_menu' => true, 'name' => 'Roles', 'icon' => 'fa fa-users', 'module_id' => 1],
            ['url' => 'roles.create', 'is_menu' => false, 'name' => 'Crear Rol', 'module_id' => 1],
            ['url' => 'roles.store', 'is_menu' => false, 'name' => 'Guardar Rol', 'module_id' => 1],
            ['url' => 'roles.edit', 'is_menu' => false, 'name' => 'Editar Rol', 'module_id' => 1],
            ['url' => 'roles.update', 'is_menu' => false, 'name' => 'Actualizar Rol', 'module_id' => 1],
            ['url' => 'roles.delete', 'is_menu' => false, 'name' => 'Eliminar Rol', 'module_id' => 1],
            ['url' => 'modules.index', 'is_menu' => true, 'name' => 'Modulos', 'icon' => 'fas fa-fw fa-th-large', 'module_id' => 1],
            ['url' => 'modules.create', 'is_menu' => false, 'name' => 'Crear Modulos', 'module_id' => 1],
            ['url' => 'modules.store', 'is_menu' => false, 'name' => 'Guardar Modulo', 'module_id' => 1],
            ['url' => 'modules.edit', 'is_menu' => false, 'name' => 'Editar Modulo', 'module_id' => 1],
            ['url' => 'modules.update', 'is_menu' => false, 'name' => 'Actualizar Modulo', 'module_id' => 1],
            ['url' => 'modules.delete', 'is_menu' => false, 'name' => 'Eliminar Modulo', 'module_id' => 1],
            ['url' => 'usuarios.index', 'is_menu' => true, 'name' => 'Usuarios', 'icon' => 'fas fa-fw fa-user', 'module_id' => 1],
            ['url' => 'usuarios.create', 'is_menu' => false, 'name' => 'Crear usuario', 'module_id' => 1],
            ['url' => 'usuarios.store', 'is_menu' => false, 'name' => 'Guardar Usuario', 'module_id' => 1],
            ['url' => 'usuarios.edit', 'is_menu' => false, 'name' => 'Editar Usuario', 'module_id' => 1],
            ['url' => 'usuarios.update', 'is_menu' => false, 'name' => 'Actualizar Usuario', 'module_id' => 1],
            ['url' => 'usuarios.changepass', 'is_menu' => false, 'name' => 'Cambiar Contraseña Usuario', 'module_id' => 1],
            ['url' => 'usuarios.destroy', 'is_menu' => false, 'name' => 'Inhabilitar / Habilitar usuario', 'module_id' => 1],
            ['url' => 'home', 'is_menu' => false, 'name' => 'Menu Principal', 'module_id' => 1],
            ['url' => 'muestras.index', 'is_menu' => true, 'name' => 'Lista de Muestras', 'icon' => 'fas fa-pump-medical', 'module_id' => 2],
            ['url' => 'muestras.exportExcel', 'is_menu' => false, 'name' => 'Exportar excel muestras', 'module_id' => 2],
            ['url' => 'muestras.create', 'is_menu' => false, 'name' => 'Crear Muestras', 'module_id' => 2],
            ['url' => 'muestras.store', 'is_menu' => false, 'name' => 'Guardar Muestra', 'module_id' => 2],
            ['url' => 'muestras.edit', 'is_menu' => false, 'name' => 'Editar Muestra', 'module_id' => 2],
            ['url' => 'muestras.update', 'is_menu' => false, 'name' => 'Actualizar Muestra', 'module_id' => 2],
            ['url' => 'muestras.show', 'is_menu' => false, 'name' => 'Mostrar detalles muestra', 'module_id' => 2],
            ['url' => 'muestras.disable', 'is_menu' => false, 'name' => 'Deshabilitar Muestra', 'module_id' => 2],
            ['url' => 'muestras.updateTipoMuestra', 'is_menu' => false, 'name' => 'Modificar Tipo muestra', 'module_id' => 2],
            ['url' => 'muestras.updateDateTimeScheduled', 'is_menu' => false, 'name' => 'Actualizar fecha estimada de la muestra', 'module_id' => 2],
            ['url' => 'muestras.updateComentarioLab', 'is_menu' => false, 'name' => 'Actualizar comentario de laboratorio a la muestra', 'module_id' => 2],
            ['url' => 'muestras.markAsElaborated', 'is_menu' => false, 'name' => 'Marcar como muestra elaborada', 'module_id' => 2],
            ['url' => 'muestras.updatePrice', 'is_menu' => false, 'name' => 'Actualizar el precio de la muestra', 'module_id' => 2],
            ['url' => 'muestras.aproveCoordinadora', 'is_menu' => false, 'name' => 'Aprobar muestra por Coordinadora', 'module_id' => 2],
            ['url' => 'muestras.aproveJefeComercial', 'is_menu' => false, 'name' => 'Aprobar muestra por Jefe Comercial', 'module_id' => 2],
            ['url' => 'muestras.aproveJefeOperaciones', 'is_menu' => false, 'name' => 'Aprobar muestra por Jefe de Operaciones', 'module_id' => 2],
            ['url' => 'muestras.status.history', 'is_menu' => false, 'name' => 'Estados de Muestra', 'description' => 'Historial de estados de la muestra', 'module_id' => 2],
            ['url' => 'doctor.index', 'is_menu' => true, 'name' => 'Doctores', 'icon' => 'fa-user-md', 'module_id' => 4],
            ['url' => 'doctor.create', 'is_menu' => false, 'name' => 'Crear Doctor', 'module_id' => 4],
            ['url' => 'doctor.store', 'is_menu' => false, 'name' => 'Guardar Doctor', 'module_id' => 4],
            ['url' => 'doctor.edit', 'is_menu' => false, 'name' => 'Editar Doctor', 'module_id' => 4],
            ['url' => 'doctor.update', 'is_menu' => false, 'name' => 'Actualizar doctor', 'module_id' => 4],
            ['url' => 'doctor.cargadata', 'is_menu' => false, 'name' => 'Cargar excel de doctores', 'module_id' => 4],
            ['url' => 'doctor.destroy', 'is_menu' => false, 'name' => 'Inhabilitar / Habilitar Doctores', 'module_id' => 4],
            ['url' => 'doctors.search', 'is_menu' => false, 'name' => 'Buscador de doctor', 'module_id' => 4],
            ['url' => 'centrosalud.index', 'is_menu' => true, 'name' => 'Centro de salud', 'icon' => 'fas fa-fw fa-h-square', 'module_id' => 4],
            ['url' => 'centrosalud.crearflorante', 'is_menu' => false, 'name' => 'Crear centro de salud desde el formulario doctor', 'module_id' => 4],
            ['url' => 'centrosalud.create', 'is_menu' => false, 'name' => 'Crear Centro de salud', 'module_id' => 4],
            ['url' => 'centrosalud.store', 'is_menu' => false, 'name' => 'Guardar Centro de salud', 'module_id' => 4],
            ['url' => 'centrosalud.edit', 'is_menu' => false, 'name' => 'Editar centro de salud', 'module_id' => 4],
            ['url' => 'centrosalud.update', 'is_menu' => false, 'name' => 'Actualizar Centro de salud', 'module_id' => 4],
            ['url' => 'centrosalud.destroy', 'is_menu' => false, 'name' => 'Eliminar centro de salud', 'module_id' => 4],
            ['url' => 'centrosalud.buscar', 'is_menu' => false, 'name' => 'Buscar centro de salud', 'module_id' => 4],
            ['url' => 'especialidad.index', 'is_menu' => true, 'name' => 'Especialidades', 'icon' => 'fas fa-fw fa-medkit', 'module_id' => 4],
            ['url' => 'especialidad.create', 'is_menu' => false, 'name' => 'Crear especialidad', 'module_id' => 4],
            ['url' => 'especialidad.store', 'is_menu' => false, 'name' => 'Guardar especialidad', 'module_id' => 4],
            ['url' => 'especialidad.edit', 'is_menu' => false, 'name' => 'Editar especialidad', 'module_id' => 4],
            ['url' => 'especialidad.update', 'is_menu' => false, 'name' => 'Actualizar especialidad', 'module_id' => 4],
            ['url' => 'especialidad.destroy', 'is_menu' => false, 'name' => 'Eliminar Especidad', 'module_id' => 4],
            ['url' => 'lista.index', 'is_menu' => true, 'name' => 'Distritos por semana', 'icon' => 'fas fa-list', 'module_id' => 4],
            ['url' => 'lista.create', 'is_menu' => false, 'name' => 'Crear distrito por semana', 'module_id' => 4],
            ['url' => 'lista.store', 'is_menu' => false, 'name' => 'Guardar distrito por semana', 'module_id' => 4],
            ['url' => 'lista.edit', 'is_menu' => false, 'name' => 'Editar distrito por semana', 'module_id' => 4],
            ['url' => 'lista.update', 'is_menu' => false, 'name' => 'Actualizar lista', 'module_id' => 4],
            ['url' => 'enrutamiento.index', 'is_menu' => true, 'name' => 'Rutas Supervisora', 'icon' => 'fas fa-list', 'module_id' => 4],
            ['url' => 'enrutamiento.store', 'is_menu' => false, 'name' => 'Crear rutas por mes', 'module_id' => 4],
            ['url' => 'enrutamiento.agregarlista', 'is_menu' => false, 'name' => 'Ver Semanas', 'module_id' => 4],
            ['url' => 'enrutamientolista.doctoresupdate', 'is_menu' => false, 'name' => 'Asignar visita a doctor', 'module_id' => 4],
            ['url' => 'enrutamientolista.store', 'is_menu' => false, 'name' => 'Crear semana y agregar doctores', 'module_id' => 4],
            ['url' => 'enrutamientolista.doctores', 'is_menu' => false, 'name' => 'Listar doctores por semana', 'module_id' => 4],
            ['url' => 'enrutamientolista.doctoresdestroy', 'is_menu' => false, 'name' => 'Eliminar visita doctor', 'module_id' => 4],
            ['url' => 'enrutamientolista.calendariovisitadora', 'is_menu' => true, 'name' => 'Calendario de rutas', 'icon' => 'fa fa-calendar', 'module_id' => 4],
            ['url' => 'ruta.mapa', 'is_menu' => true, 'name' => 'Mapa de rutas', 'icon' => 'fa fa-map', 'module_id' => 4],
            ['url' => 'rutas.detalledoctor', 'is_menu' => false, 'name' => 'Mostrar detalles del doctor', 'module_id' => 4],
            ['url' => 'rutas.guardarvisita', 'is_menu' => false, 'name' => 'Guardar visita desde el calendario', 'module_id' => 4],
            ['url' => 'rutasvisitadora.ListarMisRutas', 'is_menu' => true, 'name' => 'Lista de rutas', 'icon' => 'fa fa-list', 'module_id' => 4],
            ['url' => 'rutasvisitadora.asignar', 'is_menu' => false, 'name' => 'Asignar visita a doctor desde visitadora', 'module_id' => 4],
            ['url' => 'rutasvisitadora.buscarcmpdoctor', 'is_menu' => false, 'name' => 'Buscar CMP desde visitadora', 'module_id' => 4],
            ['url' => 'rutasvisitadora.reprogramar', 'is_menu' => false, 'name' => 'Reprogramar visita a doctor desde visitadora', 'module_id' => 4],
            ['url' => 'rutasvisitadora.guardardoctor', 'is_menu' => false, 'name' => 'Crea doctor nuevo desde visitadora', 'module_id' => 4],
            ['url' => 'rutasvisitadora.listadoctores', 'is_menu' => false, 'name' => 'Listar doctores por semana desde visitadora', 'module_id' => 4],
            ['url' => 'rutasmapa.detallesdoctor', 'is_menu' => false, 'name' => 'Detalles del doctor desde el mapa', 'module_id' => 4],
            ['url' => 'rutasmapa.guardarvisita', 'is_menu' => false, 'name' => 'Guardar visita desde el mapa', 'module_id' => 4],
            ['url' => 'doctor.aprobarVisita', 'is_menu' => false, 'name' => 'Aprobar doctor nuevo supervisora', 'module_id' => 4],
            ['url' => 'doctor.rechazarVisita', 'is_menu' => false, 'name' => 'Rechazar doctor nuevo supervisora', 'module_id' => 4],
            ['url' => 'cargarpedidos.index', 'is_menu' => true, 'name' => 'Pedidos', 'icon' => 'fas fa-fw fa-share', 'module_id' => 8],
            ['url' => 'cargarpedidos.create', 'is_menu' => false, 'name' => 'Vista de cargar pedidos por excel', 'module_id' => 8],
            ['url' => 'cargarpedidos.store', 'is_menu' => false, 'name' => 'Cargar excel de pedidos de direcciones', 'module_id' => 8],
            ['url' => 'cargarpedidos.excelarticulos', 'is_menu' => false, 'name' => 'Cargar excel de pedidos de articulos', 'module_id' => 8],
            ['url' => 'cargarpedidos.show', 'is_menu' => false, 'name' => 'Mostrar detalle del pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.actualizarPago', 'is_menu' => false, 'name' => 'Actualizar pago de los pedidos', 'module_id' => 8],
            ['url' => 'cargarpedidos.actualizarTurno', 'is_menu' => false, 'name' => 'Actualizar turno de la entrega del pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.cargarImagen', 'is_menu' => false, 'name' => 'Cargar imagenes de voucher de pedidos', 'module_id' => 8],
            ['url' => 'cargarpedidos.cargarImagenReceta', 'is_menu' => false, 'name' => 'Cargar imagen de la receta del pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.downloadWord', 'is_menu' => false, 'name' => 'Descargar word de los pedidos del día por turno', 'module_id' => 8],
            ['url' => 'cargarpedidos.eliminarFotoVoucher', 'is_menu' => false, 'name' => 'Eliminar foto del voucher del pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.edit', 'is_menu' => false, 'name' => 'Vista para editar pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.update', 'is_menu' => false, 'name' => 'Actualizar Pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.uploadfile', 'is_menu' => false, 'name' => 'Vista para cargar los vouchers y receutas de los pedidos', 'module_id' => 8],
            ['url' => 'asignarpedidos.index', 'is_menu' => true, 'name' => 'Asignar Pedidos', 'icon' => 'fas fa-fw fa-user', 'module_id' => 8],
            ['url' => 'asignarpedidos.update', 'is_menu' => false, 'name' => 'Actualizar asignación de pedido por zona', 'module_id' => 8],
            ['url' => 'historialpedidos.index', 'is_menu' => true, 'name' => 'Historial de pedidos', 'module_id' => 8],
            ['url' => 'historialpedidos.show', 'is_menu' => false, 'name' => 'Mostrar los detalle desde la vista de historial pedidos', 'module_id' => 8],
            ['url' => 'pedidosmotorizado.index', 'is_menu' => true, 'name' => 'Pedidos', 'icon' => 'fa fa-motorcycle', 'module_id' => 6],
            ['url' => 'pedidosmotorizado.edit', 'is_menu' => false, 'name' => 'Mostrar vista para actualizar entrega del pedido', 'module_id' => 6],
            ['url' => 'pedidosmotorizado.updatePedidoByMotorizado', 'is_menu' => false, 'name' => 'Actualizar entrega de los pedido', 'module_id' => 6],
            ['url' => 'pedidoslaboratorio.index', 'is_menu' => true, 'name' => 'Ordenes de Producción', 'module_id' => 5],
            ['url' => 'pedidoslaboratorio.show', 'is_menu' => false, 'name' => 'Mostrar detalles de las ordenes de producción', 'module_id' => 5],
            ['url' => 'pedidoslaboratorio.update', 'is_menu' => false, 'name' => 'Actualizar estado de la orden de produccion', 'module_id' => 5],
            ['url' => 'pedidoslaboratorio.downloadWord', 'is_menu' => false, 'name' => 'Descargar word de las ordenes de producción', 'module_id' => 5],
            ['url' => 'pedidoscontabilidad.index', 'is_menu' => true, 'name' => 'Pedidos', 'module_id' => 7],
            ['url' => 'pedidoscontabilidad.update', 'is_menu' => false, 'name' => 'Actualizar pedidos', 'module_id' => 7],
            ['url' => 'pedidoscontabilidad.downloadExcel', 'is_menu' => false, 'name' => 'Descargar excel de pedidos para contabilidad', 'module_id' => 7],
            ['url' => 'motorizado.viewFormHojaDeRuta', 'is_menu' => false, 'name' => 'Vista para descargar hoja de ruta de motorizados', 'module_id' => 8],
            ['url' => 'motorizado.exportHojaDeRuta', 'is_menu' => false, 'name' => 'Descargar excel de hoja de ruta de los motorizados', 'module_id' => 8],
            ['url' => 'pedidos.sincronizar', 'is_menu' => false, 'name' => 'Sincronizacion de doctores con pedidos de softlynn', 'module_id' => 8],
            ['url' => 'pedidos.showDeliveryStates', 'is_menu' => false, 'name' => 'Mostrar estados de entrega del pedido', 'module_id' => 8],
            ['url' => 'cargarpedidos.preview-articulos', 'is_menu' => false, 'name' => 'Vista Previa para cargar pedidos articulos', 'module_id' => 8],
            ['url' => 'cargarpedidos.confirm-articulos', 'is_menu' => false, 'name' => 'Confirmar y actualizar carga de pedidos articulos', 'module_id' => 8],
            ['url' => 'cargarpedidos.cancel-articulos', 'is_menu' => false, 'name' => 'Cancelar cargar pedidos articulos', 'module_id' => 8],
            ['url' => 'cargarpedidos.preview', 'is_menu' => false, 'name' => 'Vista Previa para cargar pedidos direcciones', 'module_id' => 8],
            ['url' => 'cargarpedidos.confirm', 'is_menu' => false, 'name' => 'Confirmar carga de pedidos direcciones', 'module_id' => 8],
            ['url' => 'cargarpedidos.cancel', 'is_menu' => false, 'name' => 'Cancelar cargar pedidos direcciones', 'module_id' => 8],
            ['url' => 'cargarpedidos.articulos.store', 'is_menu' => false, 'name' => 'Cargar excel pedidos articulos', 'module_id' => 8],
            ['url' => 'api.doctores.search', 'is_menu' => false, 'name' => 'Api para buscar doctores', 'module_id' => 8],
            ['url' => 'api.reportes.pedidos-departamento', 'is_menu' => false, 'name' => 'Api para obtener la lista de ventas por departamento', 'module_id' => 9],
            ['url' => 'reports.ventas', 'is_menu' => true, 'name' => 'Reporte de Ventas', 'description' => 'Vista del reporte de ventas', 'module_id' => 9],
            ['url' => 'reports.ventas.general', 'is_menu' => false, 'name' => 'Reporte General de Ventas', 'description' => 'API para el reporte general de doctores', 'module_id' => 9],
            ['url' => 'reports.ventas.visitadoras', 'is_menu' => false, 'name' => 'Reporte de Ventas por Visitadoras', 'description' => 'API para el reporte de ventas por visitadora', 'module_id' => 9],
            ['url' => 'reports.ventas.productos', 'is_menu' => false, 'name' => 'Reporte de Ventas por Productos', 'description' => 'API para el reporte de ventas por producto', 'module_id' => 9],
            ['url' => 'reports.ventas.provincias', 'is_menu' => false, 'name' => 'Reporte de Ventas por Provincia', 'description' => 'API para el reporte de ventas por provincia', 'module_id' => 9],
            ['url' => 'reports.doctors', 'is_menu' => true, 'name' => 'Reporte de Doctores', 'description' => 'Vista del reporte de doctores', 'module_id' => 9],
            ['url' => 'reports.doctores.doctores', 'is_menu' => false, 'name' => 'Reporte de Doctores por Doctor', 'description' => 'API para el reporte de doctores por doctor', 'module_id' => 9],
            ['url' => 'reports.doctores.tipo-doctor', 'is_menu' => false, 'name' => 'Reporte de Doctores por Tipo Doctor', 'description' => 'API para el reporte de doctores por tipo doctor (^tipo-medico^ en las tablas)', 'module_id' => 9],
            ['url' => 'reports.rutas', 'is_menu' => true, 'name' => 'Reporte de Rutas', 'description' => 'Vista del reporte de rutas', 'module_id' => 9],
            ['url' => 'reports.rutas.zones', 'is_menu' => false, 'name' => 'Reporte de Rutas por Zona', 'description' => 'API para el reporte de rutas por zona', 'module_id' => 9],
            ['url' => 'reports.muestras', 'is_menu' => true, 'name' => 'Reporte de Muestras', 'description' => 'Vista del reporte de muestras', 'module_id' => 9],
            ['url' => 'reports.muestras.general', 'is_menu' => false, 'name' => 'Reporte General de Muestras', 'description' => 'API para el reporte general de muestras', 'module_id' => 9],
            ['url' => 'reports.muestras.doctores', 'is_menu' => false, 'name' => 'Reporte de Muestras por Doctores', 'description' => 'API para el reporte de muestras por doctores', 'module_id' => 9],
            ['url' => 'rutas.zones.distritos', 'is_menu' => false, 'name' => 'Obtener los distritos por zonas', 'description' => 'API para obtener los distritos en base a la zona especificada', 'module_id' => 9],
        ];

        foreach ($views as $viewData) {
            View::factory()->withAttributes($viewData)->create();
        }
    }
}
